### ISSUE TITLE
Consider making a mini-repo on FormData, and introducing it in Unit 1 in the context of the register and login forms.

### ISSUE THREAD

**Issue by GA-MEB** [ga-wdi-boston/meta#24]
See https://github.com/ga-wdi-boston/rails-paperclip-s3/issues/1

**Comment by jrhorn424** [comment]
I'm generally in favor of this, since it minimizes querying the DOM, thereby minimizing potential spelling mistakes when submitting forms via AJAX.

@gaand mentioned on Friday that we should also be encouraging the use of `form` elements in their HTML. I was not aware that this was an issue, but it's worth noting that it's probably The Right Way™ and that FormData won't work without it.

**Comment by jrhorn424** [comment]
@gaand @MattB-GA-Boston Can this be closed since it is tracked elsewhere?

**Comment by GA-MEB** [comment]
Sure, I think so.

**Comment by gaand** [comment]
@MattB-GA-Boston: A point of developer etiquette:  if two people are asked to chime in on closing an issue, then closing it before both have responded might be seen as incourteous.

**Comment by GA-MEB** [comment]
@gaand 
I see. Sorry about that - won't happen again.
